name:                renkon
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/kayhide/renkon
license:             BSD3
author:              Hideaki KAWAI
maintainer:          kayhide@gmail.com
copyright:           2017 kayhide
category:            Web
extra-source-files:
  - README.md

dependencies:
  - ansi-terminal
  - base
  - directory
  - filemanip
  - filepath
  - foldl
  - formatting
  - lens
  - mtl
  - optparse-declarative
  - process
  - text
  - transformers

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns


library:
  source-dirs:      src

executables:
  renkon:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - renkon
